### ISSUE TITLE
Getting Open Bugs along with closed Tasks & Bugs 

### ISSUE THREAD

**Issue by mahesh3267** [immerselearning/jira-release-notes-generator#4]
Hi All, 

Great Work. 

Currently iam using this project(master branch) for jira **v7.1.7#71011-sha1:2526d7c** . Getting required information what i need. Also, getting list of all open BUGS(no Tasks) in project. Can some one please help me to stop getting this open bugs in output. 

Looking for only closed bugs,tasks for provided version.

Regards,
Mahesh K
mahesh809838@gmail.com

**Comment by Emily-Steel** [comment]
Hello Mahesh,

The only benefit this project has over the Jira version "Release notes..." button is that it adds the open bugs at the end of the list. If you don't want these then I recommend you either use [the feature in JIRA](https://confluence.atlassian.com/adminjiracloud/creating-release-notes-776636314.html) or fork this repository and remove [this line](https://github.com/immerselearning/jira-release-notes-generator/blob/master/release.rb#L31)

**Comment by mahesh3267** [comment]
Thanks for your quick response Chris. Working as expected.  

When i move the url from internal hosted jira **v7.1.7#71011-sha1:2526d7c** to cloud jira **1000.35.1**. Not Listing any closed tickets for release it is just empty. 

when i enable KNOWN_BUGS Line, i can see the open bugs from cloud jira release. Do i need to do anything in the code level to get the closed tickets ?

Please suggest.

**Comment by Emily-Steel** [comment]
Without having access to your cloud Jira instance I don't have enough information to figure this out.
My advice is to not use this code since it adds nothing for you compared to the feature included in JIRA. I recommend you follow these steps: https://confluence.atlassian.com/adminjiracloud/creating-release-notes-776636314.html
